_SCHEMA_AND_TABLES = {
    'STATUS': 'CREATE TABLE IF NOT EXISTS \
    STATUS (EXPID TEXT NOT NULL UNIQUE, STATUS TEXT NOT NULL);',

    'CONFIG': 'CREATE TABLE IF NOT EXISTS \
    CONFIG (EXPID TEXT NOT NULL UNIQUE, CONFIG TEXT NOT NULL);',

    'LOSS': 'CREATE TABLE IF NOT EXISTS \
    LOSS (EXPID TEXT NOT NULL, EPOCH INTEGER NOT NULL, KIND TEXT NOT NULL, VALUE REAL NOT NULL,\
    UNIQUE(EXPID, EPOCH, KIND));',

    'METRICS': 'CREATE TABLE IF NOT EXISTS \
    METRICS (EXPID TEXT NOT NULL, EPOCH INTEGER NOT NULL, KIND TEXT NOT NULL, VALUE REAL NOT NULL,\
    UNIQUE(EXPID, EPOCH, KIND));',

    'STATE': 'CREATE TABLE IF NOT EXISTS \
    STATE (EXPID TEXT NOT NULL, EPOCH INTEGER NOT NULL, PATH TEXT NOT NULL,\
    UNIQUE(EXPID, EPOCH, PATH));',

    'HYPERPARAMS': 'CREATE TABLE IF NOT EXISTS \
    HYPERPARAMS (EXPID TEXT NOT NULL, NAME TEXT NOT NULL, VALUE TEXT NOT NULL,\
    UNIQUE(EXPID, NAME));',

    'LEARNINGRATE': 'CREATE TABLE IF NOT EXISTS \
    LEARNINGRATE (EXPID TEXT NOT NULL, EPOCH INTEGER NOT NULL, VALUE TEXT NOT NULL,\
    UNIQUE(EXPID, EPOCH));',

    'QUALITATIVERESULTSMETA': 'CREATE TABLE IF NOT EXISTS \
    QUALITATIVERESULTSMETA (EXPID TEXT NOT NULL, PLOTID TEXT NOT NULL, VALUE TEXT NOT NULL,\
    UNIQUE(EXPID, PLOTID));',

    'QUALITATIVERESULTS': 'CREATE TABLE IF NOT EXISTS \
    QUALITATIVERESULTS (EXPID TEXT NOT NULL, EPOCH INTEGER NOT NULL, PLOTID TEXT NOT NULL, VALUE TEXT NOT NULL);',

    'EXPGROUPS': 'CREATE TABLE IF NOT EXISTS \
    EXPGROUPS (EXPID TEXT NOT NULL, GROUPNAME TEXT NOT NULL, \
    UNIQUE(EXPID, GROUPNAME));'
}

SCHEMA = list(_SCHEMA_AND_TABLES.values())
TABLES = list(_SCHEMA_AND_TABLES.keys())
